

services:
  postgres:
    image: postgres:16
    container_name: wp_labs_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student_secure_password
      POSTGRES_DB: wp_labs
    ports:
      - "5432:5432"
    volumes:
      - wp_labs_postgres:/var/lib/postgresql/data
    networks:
      - wp_labs_network
    # command: postgres -c listen_addresses='*'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: wp_labs_app
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: student
      DB_PASSWORD: student_secure_password
      DB_NAME: wp_labs
      PORT: 4200
    ports:
      - "4200:4200"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - wp_labs_network

volumes:
  wp_labs_postgres:

networks:
  wp_labs_network: